apiVersion: v2
name: octo-happiness-template-java
description: A helm chart for the basic java application
home: https://github.com/sa-mw-dach/octo-happiness-template-java
type: application
version: 0.0.9
appVersion: "v1.0.1-SNAPSHOT"
sources:
    - https://github.com/sa-mw-dach/octo-happiness-template-java
maintainers:
    - name: Georg Modzelewski
      email: georg@redhat.com
